version: '3.7'

services:
  mongodb:
    image: mongo
    restart: always
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-password}
      - MONGO_INITDB_ROOT_DATABASE=${DB_DATABASE:-delivery_database}

  delivery:
    build: ./deliveryApp
    ports:
      - 80:3000
    environment:
      - PORT=3000
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_NAME=${DB_NAME:-delivery_database}
      - DB_HOST=mongodb://mongodb:27017
    depends_on:
      - mongodb